apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::317410564812:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NLWQW2CJ2F3J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::317410564812:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-15T16:32:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1379"
  uid: c288be21-d477-4a60-9bdb-bbcfebfc6d18
